import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#ff385c',
        'primary-active': '#e00b41',
        'primary-disabled': '#ffd1da',
        'primary-error-text': '#c13515',
        'primary-error-text-hover': '#b32505',
        luxe: '#460479',
        plus: '#92174d',
        ink: '#222222',
        body: '#3f3f3f',
        muted: '#6a6a6a',
        'muted-soft': '#929292',
        hairline: '#dddddd',
        'hairline-soft': '#ebebeb',
        'border-strong': '#c1c1c1',
        canvas: '#ffffff',
        'surface-soft': '#f7f7f7',
        'surface-card': '#ffffff',
        'surface-strong': '#f2f2f2',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
        'legal-link': '#428bff',
        'star-rating': '#222222',
        scrim: '#000000',
      },
      fontSize: {
        'display-xl': '28px',
        'display-lg': '22px',
        'display-md': '21px',
        'display-sm': '20px',
        'title-md': '16px',
        'title-sm': '16px',
        'rating-display': '64px',
        'body-md': '16px',
        'body-sm': '14px',
        caption: '14px',
        'caption-sm': '13px',
        badge: '11px',
        'micro-label': '12px',
        'uppercase-tag': '8px',
        'button-md': '16px',
        'button-sm': '14px',
        link: '14px',
        'nav-link': '16px',
      },
      fontWeight: {
        'display-xl': '700',
        'display-lg': '500',
        'display-md': '700',
        'display-sm': '600',
        'title-md': '600',
        'title-sm': '500',
        'rating-display': '700',
        'body-md': '400',
        'body-sm': '400',
        caption: '500',
        'caption-sm': '400',
        badge: '600',
        'micro-label': '700',
        'uppercase-tag': '700',
        'button-md': '500',
        'button-sm': '500',
        link: '400',
        'nav-link': '600',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        base: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '64px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '14px',
        lg: '20px',
        xl: '32px',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
